---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: windows-2016
  driver_config:
    box: mwrock/Windows2016

verifier:
  name: inspec

suites:
  - name: chef_12
    provisioner:
      require_chef_omnibus: 12.19.36
    run_list:
      - recipe[chocolatey::default]
    attributes:
      chocolatey:
        install_vars:
          chocolateyVersion: 0.10.5
